// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSSHSession(arg1) {
  return window['go']['adapter']['SSHController']['CreateSSHSession'](arg1);
}

export function DeleteSSHSession(arg1) {
  return window['go']['adapter']['SSHController']['DeleteSSHSession'](arg1);
}

export function GetSSHSessionByID(arg1) {
  return window['go']['adapter']['SSHController']['GetSSHSessionByID'](arg1);
}

export function GetSSHSessions() {
  return window['go']['adapter']['SSHController']['GetSSHSessions']();
}

export function Startup(arg1) {
  return window['go']['adapter']['SSHController']['Startup'](arg1);
}

export function UpdateSSHSession(arg1) {
  return window['go']['adapter']['SSHController']['UpdateSSHSession'](arg1);
}
