// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['adapter']['UserController']['CreateUser'](
    arg1,
    arg2,
    arg3,
    arg4,
  );
}

export function LoginUser(arg1, arg2) {
  return window['go']['adapter']['UserController']['LoginUser'](arg1, arg2);
}

export function LogoutUser(arg1) {
  return window['go']['adapter']['UserController']['LogoutUser'](arg1);
}

export function Startup(arg1) {
  return window['go']['adapter']['UserController']['Startup'](arg1);
}
