// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateUser(
  arg1: string,
  arg2: string,
  arg3: string,
): Promise<void>;

export function LoginUser(
  arg1: string,
  arg2: string,
): Promise<dto.SessionResponse>;

export function LogoutUser(arg1: dto.LogoutRequest): Promise<void>;

export function Startup(arg1: context.Context): Promise<void>;
