// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateSSHSession(
  arg1: dto.CreateSSHSessionRequestDTO,
): Promise<dto.CreateSSHSessionResponseDTO>;

export function DeleteSSHSession(arg1: string): Promise<boolean>;

export function GetSSHSessionByID(
  arg1: dto.GetSessionRequestDTO,
): Promise<dto.GetSessionResponseDTO>;

export function GetSSHSessions(): Promise<Array<dto.GetSessionResponseDTO>>;

export function Startup(arg1: context.Context): Promise<void>;

export function UpdateSSHSession(
  arg1: dto.UpdateSessionRequestDTO,
): Promise<dto.UpdateSessionResponseDTO>;
