// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['controller']['UserController']['CreateUser'](arg1);
}

export function GetUser() {
  return window['go']['controller']['UserController']['GetUser']();
}

export function LoginUser(arg1) {
  return window['go']['controller']['UserController']['LoginUser'](arg1);
}

export function LogoutUser() {
  return window['go']['controller']['UserController']['LogoutUser']();
}

export function Startup(arg1) {
  return window['go']['controller']['UserController']['Startup'](arg1);
}
